#!/usr/bin/env python

################################################################################

# Std Libs
from __future__ import with_statement

import sys
import os

from os.path import join, expanduser, isabs

# 3rd Party Libs
import Pyro.core

################################################################################

sublime = Pyro.core.getProxyForURI("PYROLOC://localhost:11521/sublime")

args = sys.argv[1:]

if args:
    f = os.path.expanduser(args[0])
    if not isabs(f): f = join(os.getcwdu(), f)

    mode = os.path.exists(f) and 'r' or 'w+r'

    with open(f, mode) as fh:  edited = sublime.editBuffer(fh.read(), f)
    with open(f, 'w')  as fh:  fh.write(edited)

else:
    edited_pipe = sublime.editBuffer(sys.stdin.read())
    print edited_pipe

################################################################################
